In [2]:
# Why use NumPy? 

# w/o np arrays: 

a = [1, 2, 3, 4]
b = [10, 11, 12, 13]

a + b

[1, 2, 3, 4, 10, 11, 12, 13]

In [3]:
# lists get concatenated, not added element-by-element 

# how to do this w/o np: 

output = []

for item1, item2 in zip(a,b):
    output.append(item1 + item2)
    
# somewhat verbose ^ 
    
g = list(range(1000000))
%timeit sum(g)

6.75 ms ± 170 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
# w/ numpy

import numpy as np 

g_array = np.array(g)

%timeit np.sum(g_array)

663 µs ± 15.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
# numpy faster because python lists contain addresses but np arrays bunches the homogeneous data together in a contigouos buffer of memory 


a = np.array([1, 2, 3, 4])
b = np.array([10, 11, 12, 13])

a + b

array([11, 13, 15, 17])

In [6]:
# works with each operator: + , -, *, /, **

# attributes: 

# type of the container 
type(a) 


numpy.ndarray

In [7]:
# type of data 
a.dtype 

dtype('int64')

In [8]:
# dimensions
a.ndim 

1

In [9]:
# array shape gives tuple of length of each dimension 
a.shape

(4,)

In [10]:
# bytes per element
a.itemsize

8

In [11]:
# num of elements
a.size

4

In [12]:
# total number of bytes used
a.nbytes

32

In [13]:
# np arrays are mutable and truncate to match data type. Can fill as well. The array will take the dtype of the 
# highest type on the number hierarchy (i.e, one complex number in the initialization with everything else an int, the dtype
# would be complex)

mutable = np.array([23, 35, 3, 89])

mutable[0] = 3.4 

print(mutable[0])

mutable.fill(0)
print(mutable)

cplx = np.array([0+3j, 5, 3 ,5])
cplx.dtype

3
[0 0 0 0]


dtype('complex128')

In [14]:
c = np.array([[10, 11, 12], [20, 21, 22]])
print(c.ndim)
print(c.shape)
c

2
(2, 3)


array([[10, 11, 12],
       [20, 21, 22]])

In [15]:
# np arrays are not matrices. They are multidimensional arrays. Transposing a 1d array will not give a column vector 
# because there is no implicit second dimension. 

oned = np.array([1,2,3])

print(oned.T)

[1 2 3]


In [16]:
# syntax difference: referencing an element in a multidem array; in python you chain square brackets, in np you 
# can keep all indices in the same bracket seperated by a comma 

c[0,0]

10

In [17]:
# slicing array_name[start:non inclusive stop: optional step size], negative indices work (i.e, positions relative to 
# the end of the array)

# can ommit first element to start from beginning, ommit last to go until end 

# slicing multidem works the same way, and the referencing convention can also be written as comma seperated within 
# the same set of brackets 

# example to get middle column 



print(c[:, 1:-1])

[[11]
 [21]]


In [18]:
# masks

mask = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype = bool)

mask2 = a < 30 

a1 = np.arange(0, 80, 10)

y = a1[mask]

#can use masks for updating values as wel 

a1[mask] = 0

print(a1)

[ 0  0  0 30 40  0 60 70]


In [19]:
# cannot use syntax such as a < 8 and a > 3. Must use a.any() or a.all() to specify what the truth value of an array is. 
# bitwise operators: & and, | or , ~ not, ^ xor 
# binary operator: and, or, not 
# conclusion: can use bitwise operators on the above syntax but not binary 



In [20]:
z = np.zeros(10)
z1 = np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

res = np.hstack((z, z1))
res

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [22]:
print(np.arange(20))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])